### ISSUE TITLE
wont let me extract contents after downloading 

### ISSUE THREAD

**Issue by siroberts27** [Urban-Coalition/ArcCW_UR#1]
![File Explorer 4_5_2022 4_51_08 PM](https://user-images.githubusercontent.com/100375488/161846887-e738ddb5-5857-4225-8650-77746c0460f7.png)

says that the file is invalid and I'm not sure what is causing the problem

**Comment by Sninctbur** [comment]
Please use this section to discuss issues that directly pertain to this mod's functionality. This is not a general help forum.
