### ISSUE TITLE
Muzzle attachments excluding suppressors have a floating artifact with compact AK Barrels.

### ISSUE THREAD

**Issue by gulhon** [Urban-Coalition/ArcCW_UR#19]
![20221210163745_1](https://user-images.githubusercontent.com/36510747/206872530-9c45657b-2736-4eba-8949-81e48619f126.jpg)

Happens with Flash Hider, Basilik Compensator and both Brake muzzles.

**Comment by TheOnly8Z** [comment]
![image](https://user-images.githubusercontent.com/13565172/207092499-2df41fbb-7b77-4681-8240-597ee8ddfada.png)
fixed. muzzle booster is also now a separate bodygroup and will go away with attachment
