### ISSUE TITLE
G3 ready/draw animation has no right hand movement

### ISSUE THREAD

**Issue by Fesiug** [Urban-Coalition/ArcCW_UR#24]
https://user-images.githubusercontent.com/40924091/206928460-022ba802-341e-4ff9-a863-a359f6ed5aa6.mp4

**Comment by TheOnly8Z** [comment]
Can't replicate. Also does this happen with the always ready dev option off?

**Comment by Fesiug** [comment]
I'll try again

**Comment by Fesiug** [comment]
Uploading 2022-12-13 18-46-24.mp4…

**Comment by Fesiug** [comment]
https://user-images.githubusercontent.com/40924091/207469638-db81e426-c96c-455e-a044-62d0016628cf.mp4

**Comment by TheOnly8Z** [comment]
Okay yeah I can see it too - default viewmodel FOV is too zoomed in to see the hand.

**Comment by Fesiug** [comment]
It is fixed. 💦
