### ISSUE TITLE
Vladimir compensator does the opposite of itself

### ISSUE THREAD

**Issue by Fesiug** [Urban-Coalition/ArcCW_UR#25]
https://user-images.githubusercontent.com/40924091/206928581-fc782683-044c-46c3-a8b6-2d5834f3c082.mp4

**Comment by TheOnly8Z** [comment]
the compensator is hidden. I assume this means we only want it to show up as a default bodygroup? same with akm muzzle brake

**Comment by Fesiug** [comment]
am i stupid and this is a ignored attachment

**Comment by Fesiug** [comment]
it is💀💀💀☠️☠️☠️i have to die
