### ISSUE TITLE
AW inspect exit is fucked

### ISSUE THREAD

**Issue by Fesiug** [Urban-Coalition/ArcCW_UR#26]

**Comment by Sninctbur** [comment]
Video demonstration please?

**Comment by Fesiug** [comment]
Finishing pose is different from current idle

**Comment by TheOnly8Z** [comment]
https://user-images.githubusercontent.com/13565172/207438200-e09b5e96-f22a-4a57-9b14-60a15c743b31.mp4

**Comment by Sninctbur** [comment]
We will need to wait for Talon to adjust the inspect animations. If we can't, we might consider disabling AWP's inspect on release.

**Comment by Talon141** [comment]
Inspect will be the final thing I introduce and polish. ETA ~2-3 days methinks.

> We will need to wait for Talon to adjust the inspect animations. If we can't, we might consider disabling AWP's inspect on release.

**Comment by TheOnly8Z** [comment]
New inspect exit doesn't have this issue anymore.
