### ISSUE TITLE
MP5, HK33, several M16A2 attachments missing textures on the Linux version of GMod

### ISSUE THREAD

**Issue by gm-flatgrass** [Urban-Coalition/ArcCW_UR#28]

**Comment by Fesiug** [comment]
The native Linux build of gmod is really really bad, use Proton

**Comment by TheOnly8Z** [comment]
Likely issue with case sensitivity. Should be fixable

**Comment by Fesiug** [comment]
It'd take a while

**Comment by TheOnly8Z** [comment]
> It'd take a while

I just did it. sounds like a skill issue
