### ISSUE TITLE
m1911 empty inspect  has bullets in the chamber

### ISSUE THREAD

**Issue by BadaBingBR** [Urban-Coalition/ArcCW_UR#29]
![Sem título](https://user-images.githubusercontent.com/83316350/206950530-b9ea14a1-38b5-44dd-ba52-5faa65aa55ee.png)

**Comment by TheOnly8Z** [comment]
fixed
![image](https://user-images.githubusercontent.com/13565172/206970435-7bbdcc23-3856-4504-957b-e913c975e705.png)

**Comment by TheOnly8Z** [comment]
did not fix on usp because fix involved setting bullet bones and usp did not have those

**Comment by BadaBingBR** [comment]
actually seems like the fix didnt work, i pulled last commits and its still there 
![Sem título](https://user-images.githubusercontent.com/83316350/207058105-96418b98-4a36-4273-a207-1b742854dace.png)

**Comment by TheOnly8Z** [comment]
Appears only on inspect animation

**Comment by TheOnly8Z** [comment]
Fixed properly now.
