### ISSUE TITLE
lol funny archive corruption

### ISSUE THREAD

**Issue by lima8** [Urban-Coalition/ArcCW_UR#3]
![1cf12930f383cdd65357f28ab0c9269262cbecfc3d16356a22f127a3f76fc2c2_1](https://user-images.githubusercontent.com/104259376/174140137-68e6649c-1f6d-4581-b250-d2624d868e55.jpg)

**Comment by Fesiug** [comment]
![image](https://user-images.githubusercontent.com/40924091/178892700-897b1f90-5da4-42e4-86d3-f7a541b560c2.png)
