### ISSUE TITLE
missing AK attatchments

### ISSUE THREAD

**Issue by BigbyJM** [Urban-Coalition/ArcCW_UR#35]
I recently updated to the newest version of UR and I noticed some missing attatchments, I can no longer make the AK 12, why is that? was it on purpose or accident, or something on my side?

**Comment by Sninctbur** [comment]
The AK-12 parts and 12g and 308 conversions are being cut from the Workshop release to be moved to standalone weapons as part of an "AK expansion pack." You did nothing wrong. If you'd like to play with them anyway, enable Load Ignored Attachments in ArcCW's developer settings.

**Comment by TheOnly8Z** [comment]
use not planned for not planned stuff
