### ISSUE TITLE
Replace SPAS model

### ISSUE THREAD

**Issue by Fesiug** [Urban-Coalition/ArcCW_UR#41]
Replace the dreaded Cold War SPAS-12 model. I can do it in a day or two.

**Comment by Fesiug** [comment]
that new spas-12 model needs a lot of work

**Comment by TheOnly8Z** [comment]
What do we do about the icon? Make one for the current one and replace later?

**Comment by Fesiug** [comment]
Yeah

**Comment by Fesiug** [comment]
Wow I'm such a badass and you should have sex with me but you should ALSO and this is very important have sex with Matsilagi and Unselles
