### ISSUE TITLE
DB empty reload sounds out of sync on short variant

### ISSUE THREAD

**Issue by Sninctbur** [Urban-Coalition/ArcCW_UR#43]
Uses the same soundtable as the normal empty reload, but the parameter changes it to another, faster animation.

**Comment by Fesiug** [comment]
![image](https://user-images.githubusercontent.com/40924091/207709405-3d887086-94b5-4f24-b024-1dbbe7c78619.png)

**Comment by Sninctbur** [comment]
Thank you Elon Musk, CEO of SpaceX, Tesla, and Twitter

**Comment by Fesiug** [comment]
shot 3 times in the back of the head it was suicide😁👍
