### ISSUE TITLE
New AW re-anim need proper empty inspect

### ISSUE THREAD

**Issue by BadaBingBR** [Urban-Coalition/ArcCW_UR#47]
![gmod 2022-12-18 21-51-30](https://user-images.githubusercontent.com/83316350/208328809-4c935508-bcae-4e5a-a71d-06a68e60c891.png)
Cause right now it still shows a bullet chambered even after emptying

**Comment by TheOnly8Z** [comment]
Bullet bone is now hidden properly. Still using same animation.
