### ISSUE TITLE
AK bottom rail needs to be its own bodygroup

### ISSUE THREAD

**Issue by TheOnly8Z** [Urban-Coalition/ArcCW_UR#48]
![image](https://user-images.githubusercontent.com/13565172/208349076-9f66f419-8b47-4890-ab34-3c9a60e146ef.png)
![image](https://user-images.githubusercontent.com/13565172/208349105-765a91fa-3725-4476-b734-21adc288297d.png)

SAW Handguard needs the bottom rail. it also doesn't work with color variations on the polymer hg

**Comment by Fesiug** [comment]
On it.
