### ISSUE TITLE
LHIK breaks in ADS when using sights 

### ISSUE THREAD

**Issue by Jayrazer** [Urban-Coalition/ArcCW_UR#50]
Might be hard to notice, but using any underbarrel attachment and a sight (especially RT sights) causes left hand to flicker between UB grip and default poses. Observed on G3, MP5, AK, UD M16 and one-offs AR-57.  Using Github version of ArcCW, disabled all addons to verify it isn't a conflict.  Might be a base issue, idk.

https://user-images.githubusercontent.com/79886161/208535316-07d18e4e-52bd-45e1-9269-1d74ad26dfb4.mp4

https://user-images.githubusercontent.com/79886161/208536951-c7949553-fcc4-41fd-90d0-bab905e5170d.mp4

**Comment by Fesiug** [comment]
It's an annoying base bug, yeah

**Comment by TheOnly8Z** [comment]
https://github.com/HaodongMo/ArcCW/issues/135
